"""Tests for app.utils.diff — file filtering, patch compaction, chunking, risk scoring."""

from __future__ import annotations

import pytest

from app.utils.diff import (analyze_diff, compact_patch, score_risk,
                            should_ignore_file)

# ── should_ignore_file ───────────────────────────────────────────────


class TestShouldIgnoreFile:
    def test_ignores_lock_files(self):
        assert should_ignore_file("package-lock.json") is True
        assert should_ignore_file("yarn.lock") is True
        assert should_ignore_file("poetry.lock") is True

    def test_ignores_node_modules(self):
        assert should_ignore_file("node_modules/foo/bar.js") is True

    def test_ignores_dist(self):
        assert should_ignore_file("dist/bundle.js") is True

    def test_ignores_generated_files(self):
        assert should_ignore_file("bundle.min.js") is True
        assert should_ignore_file("src/types.generated.ts") is True
        assert should_ignore_file("src/__generated__/schema.ts") is True

    def test_ignores_binary_files(self):
        assert should_ignore_file("logo.png") is True
        assert should_ignore_file("fonts/bold.woff2") is True

    def test_keeps_normal_source_files(self):
        assert should_ignore_file("src/main.py") is False
        assert should_ignore_file("app/services/auth.js") is False
        assert should_ignore_file("lib/utils.ts") is False

    def test_extra_patterns_glob(self):
        assert should_ignore_file("tests/test_foo.py", "", ["tests/**"]) is True
        assert should_ignore_file("src/main.py", "", ["tests/**"]) is False

    def test_extra_patterns_extension_only(self):
        assert should_ignore_file("foo.spec.js", "", ["*.spec.js"]) is True
        assert should_ignore_file("foo.js", "", ["*.spec.js"]) is False

    def test_generated_annotation_in_patch(self):
        patch = "+// @generated by protobuf\n+message Foo {}"
        assert should_ignore_file("proto/foo.ts", patch) is True

    def test_empty_filename(self):
        assert should_ignore_file("") is True


# ── compact_patch ────────────────────────────────────────────────────


class TestCompactPatch:
    def test_keeps_changes_with_context(self):
        patch = "\n".join(
            [
                "@@ -1,7 +1,7 @@",
                " line1",
                " line2",
                " line3",
                "-old",
                "+new",
                " line5",
                " line6",
                " line7",
            ]
        )
        result = compact_patch(patch, keep=1)
        assert "+new" in result
        assert "-old" in result
        assert "line3" in result
        assert "line5" in result
        assert "line1" not in result
        assert "line7" not in result

    def test_empty_patch(self):
        assert compact_patch("") == ""

    def test_zero_context(self):
        patch = "\n".join(
            [
                "@@ -1,5 +1,5 @@",
                " ctx1",
                "-old",
                "+new",
                " ctx2",
                " ctx3",
            ]
        )
        result = compact_patch(patch, keep=0)
        assert "+new" in result
        assert "-old" in result
        assert "ctx1" not in result
        assert "ctx2" not in result


# ── analyze_diff ─────────────────────────────────────────────────────


class TestAnalyzeDiff:
    def test_no_files_returns_skip(self):
        r = analyze_diff([])
        assert r.skip is True
        assert r.reason == "no_files"

    def test_max_files_exceeded(self):
        files = [{"filename": f"f{i}.js", "patch": "+x"} for i in range(31)]
        r = analyze_diff(files, max_files=30)
        assert r.skip is True
        assert r.reason == "max_files_exceeded"

    def test_whitespace_only(self):
        files = [{"filename": "a.js", "patch": "+  \n-  "}]
        r = analyze_diff(files)
        assert r.skip is True
        assert r.reason == "whitespace_only"

    def test_config_only_with_flag(self):
        files = [{"filename": "package.json", "patch": '@@ -1 +1 @@\n-"1.0"\n+"1.1"'}]
        r = analyze_diff(files, skip_config_only=True)
        assert r.skip is True
        assert r.reason == "config_only"

    def test_config_only_without_flag_passes(self):
        files = [{"filename": "package.json", "patch": '@@ -1 +1 @@\n-"1.0"\n+"1.1"'}]
        r = analyze_diff(files, skip_config_only=False)
        assert r.skip is False

    def test_produces_chunks(self):
        files = [
            {"filename": "a.js", "patch": "@@ -1,3 +1,3 @@\n-old\n+new\n context"},
            {"filename": "b.js", "patch": "@@ -1,3 +1,3 @@\n-foo\n+bar\n context"},
        ]
        r = analyze_diff(files, chunk_size=50_000)
        assert r.skip is False
        assert len(r.chunk_plans) >= 1

    def test_lock_files_skipped(self):
        files = [
            {"filename": "package-lock.json", "patch": "+lots of stuff"},
            {"filename": "src/main.js", "patch": "@@ -1,1 +1,1 @@\n-old\n+new"},
        ]
        r = analyze_diff(files)
        assert r.skip is False
        skipped_names = {f["filename"] for f in r.files_skipped}
        assert "package-lock.json" in skipped_names

    def test_no_patch_skipped(self):
        files = [
            {"filename": "binary.png", "patch": ""},
            {"filename": "src/app.py", "patch": "@@ -1 +1 @@\n-a\n+b"},
        ]
        r = analyze_diff(files)
        assert r.skip is False
        skipped_names = {f["filename"] for f in r.files_skipped}
        assert "binary.png" in skipped_names

    def test_max_diff_size_exceeded(self):
        big_patch = "@@ -1 +1 @@\n" + "+x\n" * 5000
        files = [{"filename": "big.js", "patch": big_patch}]
        r = analyze_diff(files, max_diff_size=100)
        assert r.skip is True
        assert r.reason == "max_diff_size_exceeded"

    def test_chunks_sorted_by_risk_descending(self):
        files = [
            {"filename": "src/utils/format.js", "patch": "@@ -1 +1 @@\n-a\n+b"},
            {"filename": "src/auth/middleware.js", "patch": "@@ -1 +1 @@\n-x\n+y"},
        ]
        r = analyze_diff(files, chunk_size=50_000)
        assert r.skip is False
        if len(r.chunk_plans) >= 2:
            assert r.chunk_plans[0].risk_score >= r.chunk_plans[1].risk_score

    def test_extra_ignore_patterns(self):
        files = [
            {"filename": "tests/test_a.py", "patch": "@@ -1 +1 @@\n-a\n+b"},
            {"filename": "src/main.py", "patch": "@@ -1 +1 @@\n-x\n+y"},
        ]
        r = analyze_diff(files, extra_ignore_patterns=["tests/**"])
        skipped_names = {f["filename"] for f in r.files_skipped}
        assert "tests/test_a.py" in skipped_names


# ── score_risk ───────────────────────────────────────────────────────


class TestScoreRisk:
    def test_auth_file_scores_high(self):
        score, _mode = score_risk("diff content", ["src/auth/middleware.js"])
        assert score >= 2

    def test_normal_file_scores_low(self):
        score, mode = score_risk("simple change", ["src/utils/format.js"])
        assert score < 4
        assert mode == "light"

    def test_keyword_in_content(self):
        score, _mode = score_risk("checking jwt token validation", ["src/handler.js"])
        assert score >= 2

    def test_deep_review_depth_adds_score(self):
        score_deep, _ = score_risk("x", ["a.js"], review_depth="deep")
        score_fast, _ = score_risk("x", ["a.js"], review_depth="fast")
        assert score_deep > score_fast

    def test_large_chunk_adds_score(self):
        big_text = "x" * 5000
        score_big, _ = score_risk(big_text, ["a.js"])
        score_small, _ = score_risk("x", ["a.js"])
        assert score_big > score_small

    def test_many_files_adds_score(self):
        score_many, _ = score_risk("x", ["a.js", "b.js", "c.js", "d.js"])
        score_one, _ = score_risk("x", ["a.js"])
        assert score_many > score_one
