"""Diff filtering, chunking, and risk scoring.

Ported from the JS agent's ``diffFilter.js`` with identical semantics but
cleaner typing and dataclass outputs.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

# ── File-level ignore rules ──────────────────────────────────────────

IGNORED_EXACT = frozenset(
    {
        "package-lock.json",
        "yarn.lock",
        "pnpm-lock.yaml",
        "poetry.lock",
    }
)

IGNORED_DIR_PREFIXES = ("node_modules/", "dist/", "build/", "__pycache__/", ".git/")

_CONFIG_FILE_RE = re.compile(
    r"(^|/)(\.env(\..*)?|tsconfig.*\.json|jsconfig\.json|eslint.*|prettier.*"
    r"|babel\.config\.(js|cjs|mjs)|webpack\..*|vite\.config\..*"
    r"|rollup\.config\..*|pnpm-workspace\.yaml|package\.json"
    r"|Dockerfile|docker-compose\.ya?ml|\.github/workflows/.*"
    r"|pyproject\.toml|setup\.cfg|setup\.py|requirements.*\.txt)$",
    re.IGNORECASE,
)

_BINARY_EXTENSIONS = frozenset(
    {
        ".png",
        ".jpg",
        ".jpeg",
        ".gif",
        ".ico",
        ".webp",
        ".svg",
        ".woff",
        ".woff2",
        ".ttf",
        ".eot",
        ".pdf",
        ".zip",
        ".gz",
        ".tar",
        ".bin",
        ".exe",
        ".dll",
        ".so",
        ".dylib",
    }
)

_RISK_KEYWORDS_RE = re.compile(
    r"\b(auth|token|jwt|permission|role|secret|password|encrypt|decrypt"
    r"|billing|payment|migration|schema)\b",
    re.IGNORECASE,
)

_DEFAULT_RISK_PATHS = [
    "/auth/",
    "/security/",
    "/permission/",
    "/payment/",
    "/billing/",
    "/db/",
    "migration",
    "schema",
    "/config/",
    "/webhook/",
]


# ── Helpers ──────────────────────────────────────────────────────────


def _is_binary(filename: str) -> bool:
    return any(filename.lower().endswith(ext) for ext in _BINARY_EXTENSIONS)


def _is_whitespace_only(patch: str) -> bool:
    meaningful = "".join(
        line[1:]
        for line in patch.split("\n")
        if line.startswith("+") or line.startswith("-")
    )
    return len(re.sub(r"\s+", "", meaningful)) == 0


def _is_generated(filename: str, patch: str) -> bool:
    lower = filename.lower()
    if lower.endswith(".min.js") or lower.endswith(".min.css"):
        return True
    if ".generated." in lower or "_generated." in lower:
        return True
    if "/generated/" in lower or "/__generated__/" in lower:
        return True
    if re.search(
        r"@generated|auto-generated|autogenerated|generated file", patch, re.IGNORECASE
    ):
        return True
    return False


def _is_config_file(filename: str) -> bool:
    return bool(_CONFIG_FILE_RE.search(filename))


def _glob_to_regex(pattern: str) -> re.Pattern[str]:
    p = pattern if "/" in pattern else f"**/{pattern}"
    escaped = re.sub(r"[.+^${}()|[\]\\]", r"\\\g<0>", p)
    # ``**/`` means "zero or more directory segments", so we turn it into
    # an optional prefix ``(.*/)?`` instead of a mandatory ``.*``.
    escaped = escaped.replace("**/", "\x00")
    escaped = escaped.replace("**", "\x01")
    escaped = escaped.replace("*", "[^/]*")
    escaped = escaped.replace("?", "[^/]")
    # Expand sentinels *after* ``?`` replacement so the ``?`` in
    # ``(.*/)?`` is not accidentally consumed.
    escaped = escaped.replace("\x00", "(.*/)?")
    escaped = escaped.replace("\x01", ".*")
    return re.compile(f"^{escaped}$")


def should_ignore_file(
    filename: str,
    patch: str = "",
    extra_patterns: list[str] | None = None,
) -> bool:
    if not filename:
        return True
    if filename in IGNORED_EXACT:
        return True
    if any(filename.startswith(d) or f"/{d}" in filename for d in IGNORED_DIR_PREFIXES):
        return True
    if _is_binary(filename):
        return True
    if _is_generated(filename, patch):
        return True
    for pat in extra_patterns or []:
        try:
            if _glob_to_regex(pat).match(filename):
                return True
        except re.error:
            continue
    return False


# ── Patch compaction ─────────────────────────────────────────────────


def compact_patch(patch: str, keep: int = 1) -> str:
    """Rebuild a patch keeping only *keep* context lines around each change."""
    if not patch:
        return patch

    lines = patch.split("\n")
    out: list[str] = []
    hunk_lines: list[str] = []

    def flush() -> None:
        if not hunk_lines:
            return
        changed = [
            i
            for i, ln in enumerate(hunk_lines)
            if ln.startswith("+") or ln.startswith("-")
        ]
        if not changed:
            hunk_lines.clear()
            return
        include: set[int] = set()
        for idx in changed:
            for d in range(-keep, keep + 1):
                t = idx + d
                if 0 <= t < len(hunk_lines):
                    include.add(t)
        out.extend(hunk_lines[i] for i in sorted(include))
        hunk_lines.clear()

    in_hunk = False
    for line in lines:
        if line.startswith("@@"):
            flush()
            out.append(line)
            in_hunk = True
            continue
        if line.startswith("\\ No newline"):
            continue
        if in_hunk:
            hunk_lines.append(line)
        else:
            out.append(line)
    flush()
    return "\n".join(out)


# ── Chunking ─────────────────────────────────────────────────────────


def _build_chunks(entries: list[dict], chunk_size: int) -> list[dict]:
    chunks: list[dict] = []
    current = ""
    current_files: set[str] = set()

    def flush() -> None:
        nonlocal current, current_files
        if current:
            chunks.append({"text": current, "files": sorted(current_files)})
            current = ""
            current_files = set()

    for entry in entries:
        text = entry["text"]
        fname = entry["filename"]

        if len(text) > chunk_size:
            flush()
            partial = ""
            for line in text.split("\n"):
                candidate = f"{partial}\n{line}" if partial else line
                if len(candidate) > chunk_size and partial:
                    chunks.append({"text": partial, "files": [fname]})
                    partial = line
                else:
                    partial = candidate
            if partial:
                chunks.append({"text": partial, "files": [fname]})
            continue

        candidate = f"{current}\n\n{text}" if current else text
        if len(candidate) > chunk_size and current:
            flush()
            current = text
            current_files.add(fname)
        else:
            current = candidate
            current_files.add(fname)
    flush()
    return chunks


# ── Risk scoring ─────────────────────────────────────────────────────


def _estimate_complexity(chunk_text: str) -> float:
    """Estimate code complexity: 0.0-1.0 based on lines, branching, etc."""
    lines = len(chunk_text.split("\n"))
    # Count control flow complexity indicators
    complexity_keywords = ("if ", "for ", "while ", "try:", "except", "class ", "def ")
    complexity = sum(1 for kw in complexity_keywords if f"\n{kw}" in f"\n{chunk_text}")

    # Normalize: more lines and branches = higher complexity
    line_factor = min(1.0, lines / 200.0)  # ~200 lines = max complexity
    branch_factor = min(
        1.0, complexity / 10.0
    )  # ~10 control structures = high complexity

    return (line_factor + branch_factor) / 2.0


def score_risk(
    chunk_text: str,
    chunk_files: list[str],
    extra_risk_paths: list[str] | None = None,
    review_depth: str = "balanced",
) -> tuple[int, str]:
    """Return ``(score, review_mode)`` for a single chunk with multi-factor analysis.

    Considers: path criticality, code keywords, file count, complexity, and user preference.
    """
    patterns = _DEFAULT_RISK_PATHS + (extra_risk_paths or [])
    score = 0

    # Factor 1: Path-based risk (security-sensitive paths)
    for f in chunk_files:
        fl = f.lower()
        if any(p in fl for p in patterns):
            score += 2
        if _RISK_KEYWORDS_RE.search(fl):
            score += 2

    # Factor 2: Content-based risk (security/auth keywords in code)
    if _RISK_KEYWORDS_RE.search(chunk_text):
        score += 2

    # Factor 3: Scope risk (multiple files touched = broader impact)
    if len(chunk_files) > 3:
        score += 1
    elif len(chunk_files) > 1:
        score += 0.5

    # Factor 4: Complexity risk (complex code = higher review burden)
    complexity = _estimate_complexity(chunk_text)
    if complexity > 0.7:
        score += 1.5
    elif complexity > 0.4:
        score += 0.5

    # Factor 5: Size risk (large changes = more review needed)
    chunk_size = len(chunk_text)
    if chunk_size > 4500:
        score += 1
    elif chunk_size > 2000:
        score += 0.5

    # Factor 6: User preference
    if review_depth == "deep":
        score += 2
    elif review_depth == "fast":
        score = max(0, score - 1)

    # Threshold: use deep review for score >= 4.0
    mode = "deep" if score >= 4.0 else "light"
    return int(round(score)), mode


# ── Public dataclasses ───────────────────────────────────────────────


@dataclass
class ChunkPlan:
    index: int
    text: str
    files: list[str]
    risk_score: int = 0
    review_mode: str = "light"


@dataclass
class DiffAnalysis:
    skip: bool = False
    reason: str = ""
    chunk_plans: list[ChunkPlan] = field(default_factory=list)
    files_included: list[dict] = field(default_factory=list)
    files_skipped: list[dict] = field(default_factory=list)
    total_files: int = 0
    total_diff_chars: int = 0
    processable_diff_chars: int = 0
    tokens_estimated: int = 0


# ── Main entry point ─────────────────────────────────────────────────


def analyze_diff(
    files: list[dict],
    *,
    max_files: int = 30,
    max_diff_size: int = 30_000,
    chunk_size: int = 5_000,
    skip_config_only: bool = False,
    extra_ignore_patterns: list[str] | None = None,
    use_compact: bool = True,
    compact_keep: int = 1,
    review_depth: str = "balanced",
    extra_risk_paths: list[str] | None = None,
) -> DiffAnalysis:
    if not files:
        return DiffAnalysis(skip=True, reason="no_files")

    total_files = len(files)
    total_diff_chars = sum(len(f.get("patch") or "") for f in files)

    if total_files >= max_files:
        return DiffAnalysis(
            skip=True,
            reason="max_files_exceeded",
            total_files=total_files,
            total_diff_chars=total_diff_chars,
        )

    included: list[dict] = []
    skipped: list[dict] = []
    for f in files:
        fname = f.get("filename", "")
        patch = f.get("patch") or ""
        if not patch:
            skipped.append({"filename": fname, "reason": "no_patch"})
            continue
        if should_ignore_file(fname, patch, extra_ignore_patterns):
            skipped.append({"filename": fname, "reason": "ignored"})
            continue
        final_patch = compact_patch(patch, compact_keep) if use_compact else patch
        included.append({"filename": fname, "patch": final_patch})

    if not included:
        return DiffAnalysis(
            skip=True,
            reason="empty_after_filters",
            files_included=included,
            files_skipped=skipped,
            total_files=total_files,
            total_diff_chars=total_diff_chars,
        )

    if all(_is_whitespace_only(f["patch"]) for f in included):
        return DiffAnalysis(
            skip=True,
            reason="whitespace_only",
            files_included=included,
            files_skipped=skipped,
            total_files=total_files,
            total_diff_chars=total_diff_chars,
        )

    if skip_config_only and all(_is_config_file(f["filename"]) for f in included):
        return DiffAnalysis(
            skip=True,
            reason="config_only",
            files_included=included,
            files_skipped=skipped,
            total_files=total_files,
            total_diff_chars=total_diff_chars,
        )

    # Sort by directory path so co-located files land in the same chunk.
    entries = [
        {"filename": f["filename"], "text": f"--- {f['filename']}\n{f['patch']}"}
        for f in included
    ]
    entries.sort(
        key=lambda e: (
            e["filename"].rsplit("/", 1)[0] if "/" in e["filename"] else "",
            e["filename"],
        )
    )

    processable = sum(len(e["text"]) for e in entries) + 2 * max(0, len(entries) - 1)
    if processable > max_diff_size:
        return DiffAnalysis(
            skip=True,
            reason="max_diff_size_exceeded",
            files_included=included,
            files_skipped=skipped,
            total_files=total_files,
            total_diff_chars=total_diff_chars,
            processable_diff_chars=processable,
            tokens_estimated=processable // 4,
        )

    raw_chunks = _build_chunks(entries, chunk_size)
    if not raw_chunks:
        return DiffAnalysis(
            skip=True,
            reason="empty_after_filters",
            files_included=included,
            files_skipped=skipped,
            total_files=total_files,
            total_diff_chars=total_diff_chars,
        )

    plans: list[ChunkPlan] = []
    for i, c in enumerate(raw_chunks):
        risk_score, review_mode = score_risk(
            c["text"],
            c["files"],
            extra_risk_paths,
            review_depth,
        )
        plans.append(
            ChunkPlan(
                index=i,
                text=c["text"],
                files=c["files"],
                risk_score=risk_score,
                review_mode=review_mode,
            )
        )
    plans.sort(key=lambda p: p.risk_score, reverse=True)

    return DiffAnalysis(
        chunk_plans=plans,
        files_included=included,
        files_skipped=skipped,
        total_files=total_files,
        total_diff_chars=total_diff_chars,
        processable_diff_chars=processable,
        tokens_estimated=processable // 4,
    )
